/*
 * Buzzchat server API
 * Instant Messaging App server API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aymane.menfaa@insa-rennes.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;
import okhttp3.OkHttpClient;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.SseEmitter;

/**
 * API tests for SseApi
 */

public class SseApiTest {
  private final SseApi api = new SseApi();
  private MonCookieJar MonCookie;

  /**
   * GET sse/stream
   *
   * @throws ApiException if the Api call fails
   */

  @BeforeEach
  public void init() {
    MonCookie = new MonCookieJar();
    OkHttpClient.Builder builder = new OkHttpClient.Builder();
    OkHttpClient okHttpClient = builder.cookieJar(MonCookie).build();
    ApiClient apiClient = new ApiClient(okHttpClient);
    api.setApiClient(apiClient);
  }
  @Test
  public void subscribeToSSEEventsTest() throws ApiException {
    try {
      SseEmitter response = api.subscribeToSSEEvents();
      Assertions.fail();
    }
    catch (ApiException e) {
      Assertions.assertEquals(0, e.getCode());
    }
  }
}
